"""
Heart Rate Variability (HRV) Analysis Pipeline
==============================================

**Description:**
    This script extracts HRV metrics from segmented ECG/Heart Rate data generated by `segmenting.py`.
    It follows a hierarchical structure (Subject > Session > Run) to compute Time-Domain and/or Frequency-Domain
    HRV metrics for specific experiment segments (Phases, Trials, Blocks).

**Key Features:**
    1.  **Metric Computation**: Uses `neurokit2` to calculate standard HRV metrics:
        -   Time-Domain: MeanRR, SDNN, RMSSD, pNN50, etc.
        -   Frequency-Domain: LF, HF, LF/HF Ratio.
    2.  **Flexible Segmentation**: Can analyze multiple segment types:
        -   **Phases**: Short durations around specific events (e.g., 'AgentStopped').
        -   **Trials**: Full trial durations.
        -   **Blocks**: Entire experimental blocks.
    3.  **Source Flexibility**: Supports RR intervals from two sources:
        -   `bbsig`: Derived from raw ECG signal processing (more accurate).
        -   `calc`: Derived from Polar band heart rate (consumer grade).

**Inputs:**
    -   Segmented Data JSON: `data/derivatives/segmenting/sub-XXX/ses-XXX/sub-XXX_..._segmented_data.json`.
    -   Content: Contains lists of RR intervals/peaks for each defined segment.

**Outputs:**
    -   HRV Analysis Results: `data/derivatives/hrv-analysis/sub-XXX/ses-XXX/*.json`.
    -   Files are split by segment type (e.g., `hrv-phases_bbsig.json`, `hrv-trials_calc.json`).

**Usage:**
    `python code/hrv_extraction.py`
    (Edit the 'CONFIGURATION' section at the top of the script to select subjects/metrics)

"""

#%%
# Import necessary libraries
import pandas as pd
import numpy as np
import json
import gzip
from pathlib import Path
import neurokit2 as nk


#%%
# ========== CONFIGURATION ==========
# Set all the necessary parameters for inputs

root = Path(__file__).parent.parent  # project root directory
data_dir = root / "data"
derivatives_dir = data_dir / "derivatives"
segmenting_dir = derivatives_dir / "segmenting"
hrv_analysis_dir = derivatives_dir / "hrv-analysis"

# Define the list of subjects
pfxs = ["01P", "02P", "03P", "04P", "05P", "06P", "07P", "08P", "09P", "10P", "11P", "12P", "13P", "14P", "15P", "16P", "17P"]
subjects = [f"sub-{pfx}" for pfx in pfxs]

# Define sessions
sessions = ["ses-001"]

# Task name
task_name = 'TIDAL'

# ========== ANALYSIS SETTINGS ==========
# Choose which HRV metrics to compute
compute_hrv_time = True      # Compute time-domain HRV metrics
compute_hrv_freq = False     # Compute frequency-domain HRV metrics

# Choose which segments to analyze
analyze_trials = True        # Analyze trial segments
analyze_blocks = True        # Analyze block segments

# Frequency-domain HRV settings
interpolation_freq = 4       # Sampling frequency for interpolating RR intervals

# Plotting settings
show_plots = False           # Set to True to display plots during processing

#%%
# ========== HELPER FUNCTIONS ==========

def convert_peaks_to_rr(rr_dict, rr_source='rr_bbsig'):
    """
    Convert RR intervals to format for HRV analysis.

    Parameters:
    - rr_dict (dict): Dictionary with 'rr_bbsig' or 'rr_calc' keys from segmented data
    - rr_source (str): Which RR source to use - 'rr_bbsig' (ECG derived) or 'rr_calc' (Polar derived)

    Returns:
    - rrs_dict (dict): Dictionary with 'RRI' (RR intervals in ms) and 'RRI_Time' (peak timestamps in ms).
      NeuroKit2 expects RR intervals in milliseconds for accurate HRV computation.
    """

    if not rr_dict or len(rr_dict) == 0:
        return {'RRI': np.array([]), 'RRI_Time': np.array([])}

    # Extract RR intervals from the specified source
    rr_intervals = np.array(rr_dict.get(rr_source, []))

    if len(rr_intervals) == 0:
        return {'RRI': np.array([]), 'RRI_Time': np.array([])}

    # Convert RR intervals from seconds (standard LSL/Unity unit) to milliseconds (standard HRV unit)
    rr_ms = rr_intervals * 1000

    # Calculate peak timestamps as cumulative sum of RR intervals
    # This reconstructs the relative timeline of heartbeats starting from 0
    timestamps_ms = np.cumsum(rr_ms)

    # Store in NeuroKit2-compatible format
    rrs_dict = {
        'RRI': rr_ms,
        'RRI_Time': timestamps_ms
    }

    return rrs_dict


def load_segmented_data(segmented_data_path):
    """ Load segmented data from gzip-compressed JSON file.

    Parameters:
    - segmented_data_path (Path): Path to the segmented_data.json file (gzip-compressed)

    Returns:
    - segmented_data (dict): Dictionary with 'baseline', 'approach', 'recovery', 'trials', and 'blocks' keys
    """

    if not segmented_data_path.exists():
        print(f"  Warning: Segmented data file not found: {segmented_data_path}")
        return {'baseline': [], 'approach': [], 'recovery': [], 'trials': [], 'blocks': []}

    with gzip.open(segmented_data_path, 'rt', encoding='utf-8') as f:
        segmented_data = json.load(f)

    return segmented_data


def hrv_time_domain(rrs_dict, subj='', segment_type='', segment_id=''):
    """
    Compute time-domain HRV metrics from RR intervals.
    Uses NeuroKit2's `hrv_time` function to calculate standard metrics.

    Parameters:
    - rrs_dict (dict): Dictionary with 'RRI' and 'RRI_Time'
    - subj (str): Subject ID
    - segment_type (str): Type of segment ('window', 'trial', or 'block')
    - segment_id (str): Identifier for the segment

    Returns:
    - hrv_time_metrics (dict): Dictionary with computed HRV metrics, or None if not enough data.
      Metrics include: MeanRR, MeanBPM, SDNN, RMSSD, pNN50.
    """

    # Check if we have valid RR data (need at least 2 beats for difference metrics like RMSSD)
    if len(rrs_dict.get('RRI', [])) < 2:
        return None

    try:
        # Calculate Time-domain HRV metrics using NeuroKit2
        # library automatically handles outlier checking if configured, but here we pass raw RRs
        hrv_t = nk.hrv_time(rrs_dict, show=show_plots)

        # Extract and format metrics
        # We handle potential None/NaN values from NeuroKit to ensure JSON serialization safety
        hrv_time_metrics = {
            'subject': subj,
            'segment_type': segment_type,
            'segment_id': segment_id,
            'MeanRR': float(hrv_t['HRV_MeanNN'][0]) if hrv_t['HRV_MeanNN'][0] is not None else None,
            'MeanBPM': float(60000 / hrv_t['HRV_MeanNN'][0]) if hrv_t['HRV_MeanNN'][0] is not None else None,
            'MedianRR': float(hrv_t['HRV_MedianNN'][0]) if hrv_t['HRV_MedianNN'][0] is not None else None,
            'MedianBPM': float(60000 / hrv_t['HRV_MedianNN'][0]) if hrv_t['HRV_MedianNN'][0] is not None else None,
            'MinRR': float(hrv_t['HRV_MinNN'][0]) if hrv_t['HRV_MinNN'][0] is not None else None,
            'MinBPM': float(60000 / hrv_t['HRV_MaxNN'][0]) if hrv_t['HRV_MaxNN'][0] is not None else None,
            'MaxRR': float(hrv_t['HRV_MaxNN'][0]) if hrv_t['HRV_MaxNN'][0] is not None else None,
            'MaxBPM': float(60000 / hrv_t['HRV_MinNN'][0]) if hrv_t['HRV_MinNN'][0] is not None else None,
            'SDNN': float(hrv_t['HRV_SDNN'][0]) if hrv_t['HRV_SDNN'][0] is not None else None,
            'SDSD': float(hrv_t['HRV_SDSD'][0]) if hrv_t['HRV_SDSD'][0] is not None else None,
            'RMSSD': float(hrv_t['HRV_RMSSD'][0]) if hrv_t['HRV_RMSSD'][0] is not None else None,
            'pnn50': float(hrv_t['HRV_pNN50'][0]) if hrv_t['HRV_pNN50'][0] is not None else None
        }
        return hrv_time_metrics
    except Exception as e:
        print(f"  Error computing time-domain HRV metrics: {e}")
        return None


def hrv_frequency_domain(rrs_dict, subj='', segment_type='', segment_id='', interpolation_rate=4):
    """ Compute frequency-domain HRV metrics from RR intervals.

    Parameters:
    - rrs_dict (dict): Dictionary with 'RRI' and 'RRI_Time'
    - subj (str): Subject ID
    - segment_type (str): Type of segment ('window', 'trial', or 'block')
    - segment_id (str): Identifier for the segment
    - interpolation_rate (float): Sampling frequency for interpolating RR intervals

    Returns:
    - hrv_freq_metrics (dict): Dictionary with computed HRV metrics, or None if not enough data
    """

    # Check if we have valid RR data
    if len(rrs_dict.get('RRI', [])) < 2:
        return None

    try:
        # Calculate Frequency-domain HRV metrics using NeuroKit2
        hrv_f = nk.hrv_frequency(rrs_dict, interpolation_rate=interpolation_rate,
                                 normalize=False, psd_method='welch', show=show_plots)

        # Extract and format metrics
        hrv_freq_metrics = {
            'subject': subj,
            'segment_type': segment_type,
            'segment_id': segment_id,
            'VLF': float(hrv_f['HRV_VLF'][0]) if hrv_f['HRV_VLF'][0] is not None else None,
            'LF': float(hrv_f['HRV_LF'][0]) if hrv_f['HRV_LF'][0] is not None else None,
            'HF': float(hrv_f['HRV_HF'][0]) if hrv_f['HRV_HF'][0] is not None else None,
            'LF/HF': float(hrv_f['HRV_LFHF'][0]) if hrv_f['HRV_LFHF'][0] is not None else None,
            'LFn': float(hrv_f['HRV_LFn'][0]) if hrv_f['HRV_LFn'][0] is not None else None,
            'HFn': float(hrv_f['HRV_HFn'][0]) if hrv_f['HRV_HFn'][0] is not None else None,
            'LnHF': float(hrv_f['HRV_LnHF'][0]) if hrv_f['HRV_LnHF'][0] is not None else None
        }
        return hrv_freq_metrics
    except Exception as e:
        print(f"  Error computing frequency-domain HRV metrics: {e}")
        return None

def save_hrv_results(hrv_results, output_dir, subject, session, run, segment_type, rr_source=''):
    """ Save HRV results for a specific segment type to JSON file.

    Parameters:
    - hrv_results (list): List of HRV metric dictionaries
    - output_dir (Path): Output directory
    - subject (str): Subject ID
    - session (str): Session ID
    - run (str): Run identifier
    - segment_type (str): Type of segment ('windows', 'trials', or 'blocks')
    - rr_source (str): RR source identifier ('bbsig' or 'calc')
    """

    if not hrv_results:
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    # Add RR source to filename if specified
    if rr_source:
        output_file = output_dir / f"{subject}_{session}_task-TIDAL_{run}_hrv-{segment_type}_{rr_source}.json"
    else:
        output_file = output_dir / f"{subject}_{session}_task-TIDAL_{run}_hrv-{segment_type}.json"

    with open(output_file, 'w') as f:
        json.dump(hrv_results, f, indent=4)

    return output_file


#%%
# ========== MAIN PROCESSING LOOP ==========

print("=" * 80)
print("HRV EXTRACTION PIPELINE")
print("=" * 80)
print(f"Time-domain HRV: {compute_hrv_time}")
print(f"Frequency-domain HRV: {compute_hrv_freq}")
print(f"Analyze trials: {analyze_trials}")
print(f"Analyze blocks: {analyze_blocks}")
print("=" * 80)

# Loop through subjects, sessions, and runs
for subject in subjects:
    for session in sessions:
        # Find all available runs for this subject/session
        subject_dir = segmenting_dir / subject / session

        if not subject_dir.exists():
            continue

        # Get all segmented data files for this subject/session
        segmented_files = sorted(subject_dir.glob(f"{subject}_{session}_task-TIDAL_run-*_segmented_data.json"))

        if not segmented_files:
            continue

        print(f"\n{subject} {session}:")

        for segmented_file in segmented_files:
            # Extract run number from filename
            run = segmented_file.name.split('task-TIDAL_')[1].split('_segmented')[0]

            # Load segmented data
            segmented_data = load_segmented_data(segmented_file)

            # Initialize results for each segment type and RR source
            trials_hrv_time_bbsig = []
            trials_hrv_freq_bbsig = []
            trials_hrv_time_calc = []
            trials_hrv_freq_calc = []
            blocks_hrv_time_bbsig = []
            blocks_hrv_freq_bbsig = []
            blocks_hrv_time_calc = []
            blocks_hrv_freq_calc = []

            # ========== PROCESS TRIALS ==========
            if analyze_trials and 'trials' in segmented_data:
                print(f"  Processing trials for {run}...")
                for trial_idx, trial in enumerate(segmented_data['trials']):
                    # Process both RR sources
                    for rr_source in ['rr_bbsig', 'rr_calc']:
                        rr_label = 'bbsig' if rr_source == 'rr_bbsig' else 'calc'

                        # Convert RR intervals to HRV format
                        rrs_dict = convert_peaks_to_rr(trial.get('ecg_peaks', {}), rr_source=rr_source)

                        # Compute HRV metrics if we have valid data
                        if len(rrs_dict['RRI']) > 0:
                            # Time-domain HRV
                            if compute_hrv_time:
                                trial_hrv_time = hrv_time_domain(
                                    rrs_dict,
                                    subj=subject,
                                    segment_type='trial',
                                    segment_id=trial.get('trial', f"trial_{trial_idx}")
                                )
                                if trial_hrv_time is not None:
                                    # Add timing and source information
                                    trial_hrv_time['trial_start'] = trial.get('trial_start')
                                    trial_hrv_time['trial_end'] = trial.get('trial_end')
                                    trial_hrv_time['trial'] = trial.get('trial')
                                    trial_hrv_time['run'] = run
                                    trial_hrv_time['session'] = session
                                    trial_hrv_time['rr_source'] = rr_source
                                    if rr_label == 'bbsig':
                                        trials_hrv_time_bbsig.append(trial_hrv_time)
                                    else:
                                        trials_hrv_time_calc.append(trial_hrv_time)

                            # Frequency-domain HRV
                            if compute_hrv_freq:
                                trial_hrv_freq = hrv_frequency_domain(
                                    rrs_dict,
                                    subj=subject,
                                    segment_type='trial',
                                    segment_id=trial.get('trial', f"trial_{trial_idx}"),
                                    interpolation_rate=interpolation_freq
                                )
                                if trial_hrv_freq is not None:
                                    # Add timing and source information
                                    trial_hrv_freq['trial_start'] = trial.get('trial_start')
                                    trial_hrv_freq['trial_end'] = trial.get('trial_end')
                                    trial_hrv_freq['trial'] = trial.get('trial')
                                    trial_hrv_freq['run'] = run
                                    trial_hrv_freq['session'] = session
                                    trial_hrv_freq['rr_source'] = rr_source
                                    if rr_label == 'bbsig':
                                        trials_hrv_freq_bbsig.append(trial_hrv_freq)
                                    else:
                                        trials_hrv_freq_calc.append(trial_hrv_freq)

                print(f"    bbsig: {len(trials_hrv_time_bbsig)} time-domain, {len(trials_hrv_freq_bbsig)} freq-domain")
                print(f"    calc:  {len(trials_hrv_time_calc)} time-domain, {len(trials_hrv_freq_calc)} freq-domain")

            # ========== PROCESS BLOCKS ==========
            if analyze_blocks and 'blocks' in segmented_data:
                print(f"  Processing blocks for {run}...")
                for block_idx, block in enumerate(segmented_data['blocks']):
                    # Process both RR sources
                    for rr_source in ['rr_bbsig', 'rr_calc']:
                        rr_label = 'bbsig' if rr_source == 'rr_bbsig' else 'calc'

                        # Convert RR intervals to HRV format
                        rrs_dict = convert_peaks_to_rr(block.get('ecg_peaks', {}), rr_source=rr_source)

                        # Compute HRV metrics if we have valid data
                        if len(rrs_dict['RRI']) > 0:
                            # Time-domain HRV
                            if compute_hrv_time:
                                block_hrv_time = hrv_time_domain(
                                    rrs_dict,
                                    subj=subject,
                                    segment_type='block',
                                    segment_id=block.get('block', f"block_{block_idx}")
                                )
                                if block_hrv_time is not None:
                                    # Add timing and source information
                                    block_hrv_time['block_start'] = block.get('block_start')
                                    block_hrv_time['block_end'] = block.get('block_end')
                                    block_hrv_time['block'] = block.get('block')
                                    block_hrv_time['run'] = run
                                    block_hrv_time['session'] = session
                                    block_hrv_time['rr_source'] = rr_source
                                    if rr_label == 'bbsig':
                                        blocks_hrv_time_bbsig.append(block_hrv_time)
                                    else:
                                        blocks_hrv_time_calc.append(block_hrv_time)

                            # Frequency-domain HRV
                            if compute_hrv_freq:
                                block_hrv_freq = hrv_frequency_domain(
                                    rrs_dict,
                                    subj=subject,
                                    segment_type='block',
                                    segment_id=block.get('block', f"block_{block_idx}"),
                                    interpolation_rate=interpolation_freq
                                )
                                if block_hrv_freq is not None:
                                    # Add timing and source information
                                    block_hrv_freq['block_start'] = block.get('block_start')
                                    block_hrv_freq['block_end'] = block.get('block_end')
                                    block_hrv_freq['block'] = block.get('block')
                                    block_hrv_freq['run'] = run
                                    block_hrv_freq['session'] = session
                                    block_hrv_freq['rr_source'] = rr_source
                                    if rr_label == 'bbsig':
                                        blocks_hrv_freq_bbsig.append(block_hrv_freq)
                                    else:
                                        blocks_hrv_freq_calc.append(block_hrv_freq)

                print(f"    bbsig: {len(blocks_hrv_time_bbsig)} time-domain, {len(blocks_hrv_freq_bbsig)} freq-domain")
                print(f"    calc:  {len(blocks_hrv_time_calc)} time-domain, {len(blocks_hrv_freq_calc)} freq-domain")

            # ========== SAVE RESULTS ==========
            output_dir = hrv_analysis_dir / subject / session

            # Save trials
            if analyze_trials:
                if compute_hrv_time and trials_hrv_time_bbsig:
                    file_path = save_hrv_results(trials_hrv_time_bbsig, output_dir, subject, session, run, 'trials_time', 'bbsig')
                    print(f"    Saved: {file_path.name}")
                if compute_hrv_time and trials_hrv_time_calc:
                    file_path = save_hrv_results(trials_hrv_time_calc, output_dir, subject, session, run, 'trials_time', 'calc')
                    print(f"    Saved: {file_path.name}")
                if compute_hrv_freq and trials_hrv_freq_bbsig:
                    file_path = save_hrv_results(trials_hrv_freq_bbsig, output_dir, subject, session, run, 'trials_freq', 'bbsig')
                    print(f"    Saved: {file_path.name}")
                if compute_hrv_freq and trials_hrv_freq_calc:
                    file_path = save_hrv_results(trials_hrv_freq_calc, output_dir, subject, session, run, 'trials_freq', 'calc')
                    print(f"    Saved: {file_path.name}")

            # Save blocks
            if analyze_blocks:
                if compute_hrv_time and blocks_hrv_time_bbsig:
                    file_path = save_hrv_results(blocks_hrv_time_bbsig, output_dir, subject, session, run, 'blocks_time', 'bbsig')
                    print(f"    Saved: {file_path.name}")
                if compute_hrv_time and blocks_hrv_time_calc:
                    file_path = save_hrv_results(blocks_hrv_time_calc, output_dir, subject, session, run, 'blocks_time', 'calc')
                    print(f"    Saved: {file_path.name}")
                if compute_hrv_freq and blocks_hrv_freq_bbsig:
                    file_path = save_hrv_results(blocks_hrv_freq_bbsig, output_dir, subject, session, run, 'blocks_freq', 'bbsig')
                    print(f"    Saved: {file_path.name}")
                if compute_hrv_freq and blocks_hrv_freq_calc:
                    file_path = save_hrv_results(blocks_hrv_freq_calc, output_dir, subject, session, run, 'blocks_freq', 'calc')
                    print(f"    Saved: {file_path.name}")

print("\n" + "=" * 80)
print("HRV EXTRACTION COMPLETE!")
print("=" * 80)
# %%
