"""
LSL XDF Recording Validator
===========================

**Description:**
    This script is a diagnostic tool for inspecting raw XDF files generated by LabRecorder.
    It provides a detailed summary of all streams contained within a file, allowing you to quickly
    verify that your data recording setup functioned correctly.

**Use as a Validation Tool:**
    Run this script immediately after a recording session or when troubleshooting data issues to check:
    1.  **Stream Presence**: Are all expected streams (e.g., "Polar", "Unity", "BrainVision RDA") present?
    2.  **Data Integrity**:
        -   Do the streams have the correct number of channels?
        -   Is the *Effective Sampling Rate* close to the *Nominal Sampling Rate*? (Large discrepancies indicate data loss or jitter).
        -   Is the recording duration consistent across all streams?
    3.  **Event Markers**: Are the expected event markers (e.g., 'AgentAppeared', 'BlockStart') present in the event stream?

**Inputs:**
    -   Path to a `.xdf` file (via command line argument).

**Outputs:**
    -   Prints a structured report to the console detailing every stream found in the file.
    -   Optionally plots stream data or explores it as a DataFrame.

**Usage:**
    `python code/inspect_xdf.py path/to/file.xdf`
    `python code/inspect_xdf.py path/to/file.xdf --info --dataframe`
"""

import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pyxdf


def pick_stream(streams, wanted_name=None):
    """Pick a stream by its info['name'], else return the first stream."""
    if wanted_name:
        for s in streams:
            name = s["info"]["name"][0] if "name" in s["info"] else ""
            if name == wanted_name:
                return s
        raise ValueError(f"Stream named '{wanted_name}' not found in XDF.")
    return streams[0]


def get_channel_labels(stream):
    """Try to extract channel labels from XDF metadata; fallback to Ch1..ChN."""
    try:
        desc = stream["info"]["desc"][0]
        chans = desc["channels"][0]["channel"]
        labels = []
        for ch in chans:
            if "label" in ch and len(ch["label"]) > 0:
                labels.append(ch["label"][0])
            else:
                labels.append(None)
        if any(l is not None for l in labels):
            return [l if l else f"Ch{i+1}" for i, l in enumerate(labels)]
    except Exception:
        pass

    n_ch = stream["time_series"].shape[1] if stream["time_series"].ndim > 1 else 1
    return [f"Ch{i+1}" for i in range(n_ch)]


def stream_to_dataframe(stream, start_offset=0.0, duration=None, global_t0=None):
    """
    Convert an XDF stream to a pandas DataFrame with timestamps and channel labels.

    Args:
        stream: XDF stream dict
        start_offset: Start time offset in seconds
        duration: Optional duration in seconds to limit the data
        global_t0: Optional global time reference (for alignment with other streams).
                   If None, uses this stream's first timestamp as reference.

    Returns:
        DataFrame with timestamp index and channel columns
    """
    X = np.asarray(stream["time_series"])
    t = stream["time_stamps"].astype(np.float64)

    # Ensure 2D: (samples, channels)
    if X.ndim == 1:
        X = X[:, None]

    # Make time relative (seconds from reference)
    if global_t0 is None:
        t0 = t[0]
    else:
        t0 = global_t0
    t = t - t0

    # Select time window
    start = max(start_offset, 0.0)
    end = None if duration is None else (start + duration)

    mask = (t >= start) if end is None else ((t >= start) & (t <= end))
    t_sel = t[mask]
    X_sel = X[mask, :]

    # Get labels
    labels = get_channel_labels(stream)

    # Create DataFrame
    df = pd.DataFrame(X_sel, columns=labels[:X_sel.shape[1]])
    df.insert(0, 'timestamp', t_sel)
    df = df.reset_index(drop=True)

    return df



def is_event_stream(stream):
    """
    Heuristically detect if a stream contains events (sparse markers) rather than continuous data.
    Events typically have very few samples compared to their time span and nominal sampling rate.
    """
    try:
        if len(stream["time_stamps"]) == 0:
            return False

        srate = float(stream["info"]["nominal_srate"][0]) if "nominal_srate" in stream["info"] else 1.0
        if srate == 0:
            srate = 1.0

        duration = stream["time_stamps"][-1] - stream["time_stamps"][0]
        n_samples = len(stream["time_stamps"])
        expected_samples = duration * srate

        # If actual samples are < 10% of expected, it's probably an event stream
        sparsity_ratio = n_samples / expected_samples if expected_samples > 0 else 1.0
        return sparsity_ratio < 0.1
    except:
        return False


def plot_multiple_streams(streams, start_offset=0.0, duration=None, event_streams=None):
    """
    Plot all streams in a single figure with subplots, aligned in time.
    Event streams are plotted as vertical lines/markers instead of continuous lines.

    Args:
        streams: List of XDF stream dicts
        start_offset: Start time offset in seconds
        duration: Optional duration in seconds to limit the data
        event_streams: Optional list of stream indices to treat as events
    """
    # Filter out empty streams
    valid_streams = []
    for s in streams:
        if len(s["time_stamps"]) > 0:
            valid_streams.append(s)
        else:
            name = s["info"]["name"][0] if "name" in s["info"] else "Unknown"
            print(f"  Warning: Skipping empty stream '{name}' (0 samples)")

    if not valid_streams:
        print("Error: No streams with data to plot!")
        return

    # Calculate global time reference (earliest timestamp across all streams)
    global_t0 = min(s["time_stamps"][0] for s in valid_streams)

    # Calculate global time range
    all_times_relative = []
    for s in valid_streams:
        t_rel = s["time_stamps"].astype(np.float64) - global_t0
        all_times_relative.append(t_rel)

    global_tmin = min(t.min() for t in all_times_relative)
    global_tmax = max(t.max() for t in all_times_relative)

    # Apply start and duration filters
    start = max(start_offset, global_tmin)
    end = None if duration is None else (start + duration)
    if end is None:
        end = global_tmax

    n_streams = len(valid_streams)
    fig, axes = plt.subplots(n_streams, 1, figsize=(14, 3 * n_streams))

    # Handle single stream case
    if n_streams == 1:
        axes = [axes]

    for idx, (stream, t_rel) in enumerate(zip(valid_streams, all_times_relative)):
        name = stream["info"]["name"][0] if "name" in stream["info"] else f"Stream_{idx}"
        X = np.asarray(stream["time_series"])

        # Ensure 2D
        if X.ndim == 1:
            X = X[:, None]

        # Select time window using global time reference
        mask = (t_rel >= start) & (t_rel <= end)
        t_sel = t_rel[mask]
        X_sel = X[mask, :]

        if len(t_sel) == 0:
            print(f"  Warning: No data in selected time window for stream '{name}'")
            ax = axes[idx]
            ax.set_title(f"Stream: {name} (no data in window)")
            ax.set_xlabel("Time (s)")
            ax.set_ylabel("Value")
            ax.grid(True, alpha=0.3)
            continue

        labels = get_channel_labels(stream)
        ax = axes[idx]

        # Check if this is an event stream (sparse data with discrete markers)
        is_event = event_streams and idx in event_streams or (event_streams is None and is_event_stream(stream))

        if is_event:
            # Plot events as vertical lines at each timestamp
            for ch_idx in range(X_sel.shape[1]):
                for t_val in t_sel:
                    ax.axvline(x=t_val, alpha=0.6, linewidth=2, label=labels[ch_idx] if ch_idx < len(labels) else f"Ch{ch_idx+1}")
                # Remove duplicate labels
                handles, labels_set = ax.get_legend_handles_labels()
                by_label = dict(zip(labels_set, handles))
                ax.legend(by_label.values(), by_label.keys(), loc="upper right", fontsize=8)
            ax.set_ylim(-0.5, 1)
        else:
            # Plot continuous data as normal lines
            for ch_idx in range(X_sel.shape[1]):
                ax.plot(t_sel, X_sel[:, ch_idx], label=labels[ch_idx] if ch_idx < len(labels) else f"Ch{ch_idx+1}", alpha=0.8)
            ax.legend(loc="upper right", fontsize=8)

        ax.set_title(f"Stream: {name}" + (" (Events)" if is_event else ""))
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Value")
        ax.grid(True, alpha=0.3)

    # Set all x-axes to the same range
    for ax in axes:
        ax.set_xlim(start, end)

    plt.tight_layout()
    plt.show()


def main():
    parser = argparse.ArgumentParser(description="Load an XDF file and plot or explore a stream.")
    parser.add_argument("xdf_path", help="Path to .xdf file")
    parser.add_argument("--stream", default=None, help="Exact LSL stream name to plot (info.name)")
    parser.add_argument("--seconds", type=float, default=None, help="Plot only first N seconds")
    parser.add_argument("--start", type=float, default=0.0, help="Start time offset in seconds (relative to first sample)")
    parser.add_argument("--dataframe", action="store_true", help="Convert stream to DataFrame for exploration (instead of plotting)")
    parser.add_argument("--info", action="store_true", help="Show DataFrame info and basic statistics")
    parser.add_argument("--all-streams", action="store_true", help="Plot all streams simultaneously in one figure")
    parser.add_argument("--event-streams", default=None, help="Comma-separated stream indices to treat as events (e.g., '0,2')")
    args = parser.parse_args()

    # Parse event stream indices
    event_streams = None
    if args.event_streams:
        try:
            event_streams = [int(x.strip()) for x in args.event_streams.split(',')]
        except ValueError:
            print("Error: --event-streams must be comma-separated integers (e.g., '0,2')")
            return

    streams, header = pyxdf.load_xdf(args.xdf_path)

    print(f"\nLoaded: {args.xdf_path}")
    print(f"Found {len(streams)} streams:\n")
    for i, s in enumerate(streams):
        name = s["info"]["name"][0] if "name" in s["info"] else "?"
        stype = s["info"]["type"][0] if "type" in s["info"] else "?"
        ch = int(s["info"]["channel_count"][0]) if "channel_count" in s["info"] else "?"
        srate = float(s["info"]["nominal_srate"][0]) if "nominal_srate" in s["info"] else 0.0
        n = len(s["time_stamps"])
        is_event = s["time_stamps"].size > 0 and is_event_stream(s)
        event_marker = " (detected as EVENT stream)" if is_event else ""
        print(f"[{i}] name='{name}' type='{stype}' ch={ch} srate={srate}Hz samples={n}{event_marker}")

    # If --all-streams is set, plot all and exit
    if args.all_streams:
        print("\nPlotting all streams...")
        plot_multiple_streams(streams, args.start, args.seconds, event_streams)
        return

    stream = pick_stream(streams, args.stream)

    name = stream["info"]["name"][0] if "name" in stream["info"] else "selected_stream"

    # Calculate global time reference for consistency with --all-streams
    valid_streams = [s for s in streams if len(s["time_stamps"]) > 0]
    global_t0 = min(s["time_stamps"][0] for s in valid_streams) if valid_streams else None

    # Convert to DataFrame (using global time reference for alignment)
    df = stream_to_dataframe(stream, args.start, args.seconds, global_t0=global_t0)

    if args.dataframe:
        # Interactive DataFrame exploration
        print(f"\n{'='*60}")
        print(f"Stream: {name}")
        print(f"{'='*60}")

        print(f"\nShape: {df.shape[0]} samples × {df.shape[1]} columns")
        print(f"Time range: {df['timestamp'].min():.3f}s to {df['timestamp'].max():.3f}s")
        print(f"\nFirst 10 rows:")
        print(df.head(10))

        if args.info:
            print(f"\n{'='*60}")
            print("DataFrame Info:")
            print(f"{'='*60}")
            print(df.info())

            print(f"\n{'='*60}")
            print("Basic Statistics:")
            print(f"{'='*60}")
            print(df.describe())

        # Option to save
        print(f"\nDataFrame available as 'df' variable")
        try:
            # Try to launch interactive mode if in Jupyter-like environment
            import code
            code.interact(local={"df": df, "pd": pd, "np": np})
        except:
            # If not interactive shell, just print summary
            print(f"To save to CSV: df.to_csv('output.csv', index=False)")
    else:
        # Original plotting behavior
        X = np.asarray(stream["time_series"])
        t = stream["time_stamps"].astype(np.float64)

        # Ensure 2D: (samples, channels)
        if X.ndim == 1:
            X = X[:, None]

        # Make time relative (seconds from first sample)
        t0 = t[0]
        t = t - t0

        # Select time window
        start = max(args.start, 0.0)
        end = None if args.seconds is None else (start + args.seconds)

        mask = (t >= start) if end is None else ((t >= start) & (t <= end))
        t_sel = t[mask]
        X_sel = X[mask, :]

        if len(t_sel) == 0:
            raise RuntimeError("No samples in the selected time window. Try different --start/--seconds.")

        labels = get_channel_labels(stream)

        # Plot
        plt.figure(figsize=(12, 6))
        for ch_idx in range(X_sel.shape[1]):
            plt.plot(t_sel, X_sel[:, ch_idx], label=labels[ch_idx] if ch_idx < len(labels) else f"Ch{ch_idx+1}")

        plt.title(f"XDF Stream: {name}")
        plt.xlabel("Time (s)")
        plt.ylabel("Value")
        plt.legend(loc="upper right", ncols=2, fontsize=9)
        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    main()
